name: ci-release
on:
  release:
    branches:
      - master
    types:
      - published
    tags:
      - 'v*'

jobs:
  tag-submission-image:
    name: "Tag the submission image on ECR with the version"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TOOLING_PUSHECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TOOLING_PUSHECR }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: "Get tag value"
        id: get-tag-value
        run: |
          echo "::set-output name=tag::${{ github.event.release.tag_name }}"
      - name: "Pull image from ECR, tag it and push it"
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_HOST }}
          docker pull ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}
          docker tag ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA} ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${{ steps.get-tag-value.outputs.tag }}
          docker push ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${{ steps.get-tag-value.outputs.tag }}

  deploy-prd-submission-int:
    name: "Deploy the internal submission service to the prd environment"
    runs-on: ubuntu-latest
    needs:
      - tag-submission-image
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRD_PUSHECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD_PUSHECR }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Retrieve Task Definition for external service on PRD
        run: |
          aws ecs describe-task-definition --task-definition "${{ secrets.ECS_TASK_FAMILY_SUBMISSION_PRD }}-int" --query taskDefinition > task-definition.json
      - name: Set image name as output
        id: set-image-output
        run: |
          echo "::set-output name=image::${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}"
      - name: Update Task Definition for PRD with new image
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: "${{ secrets.ECS_CONTAINER_NAME_SUBMISSION_PRD }}-int"
          image: "${{ steps.set-image-output.outputs.image }}"
      - name: Get service to update
        id: set-service-output
        run: |
          echo "::set-output name=service::$(aws ecs list-services --cluster ${{ secrets.CLUSTER_NAME_PRD }} --output text | grep SubmissionInt | awk -F'/' '{print $2}')"
      - name: Deploy services with new task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ steps.set-service-output.outputs.service }}
          cluster: ${{ secrets.CLUSTER_NAME_PRD }}
          wait-for-service-stability: false

  deploy-prd-submission-quartz:
    name: "Deploy the quartz submission service to the prd environment"
    runs-on: ubuntu-latest
    needs:
      - tag-submission-image
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRD_PUSHECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD_PUSHECR }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Retrieve Task Definition for external service on PRD
        run: |
          aws ecs describe-task-definition --task-definition "${{ secrets.ECS_TASK_FAMILY_SUBMISSION_PRD }}-quartz" --query taskDefinition > task-definition.json
      - name: Set image name as output
        id: set-image-output
        run: |
          echo "::set-output name=image::${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}"
      - name: Update Task Definition for PRD with new image
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: "${{ secrets.ECS_CONTAINER_NAME_SUBMISSION_PRD }}-quartz"
          image: "${{ steps.set-image-output.outputs.image }}"
      - name: Get service to update
        id: set-service-output
        run: |
          echo "::set-output name=service::$(aws ecs list-services --cluster ${{ secrets.CLUSTER_NAME_PRD }} --output text | grep SubmissionQua | awk -F'/' '{print $2}')"
      - name: Deploy services with new task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ steps.set-service-output.outputs.service }}
          cluster: ${{ secrets.CLUSTER_NAME_PRD }}
          wait-for-service-stability: false

  deploy-prd-submission:
    name: "Deploy the external submission service to the prd environment"
    runs-on: ubuntu-latest
    needs:
      - tag-submission-image
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRD_PUSHECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD_PUSHECR }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Retrieve Task Definition for external service on PRD
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_FAMILY_SUBMISSION_PRD }} --query taskDefinition > task-definition.json
      - name: Show task definition
        run: |
          cat task-definition.json
      - name: Set image name as output
        id: set-image-output
        run: |
          echo "::set-output name=image::${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}"
      - name: Update Task Definition for PRD with new image
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: "${{ secrets.ECS_CONTAINER_NAME_SUBMISSION_PRD }}"
          image: "${{ steps.set-image-output.outputs.image }}"
        env:
          IMAGE: "${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}"
      - name: Get service to update
        id: set-service-output
        run: |
          echo "::set-output name=service::$(aws ecs list-services --cluster ${{ secrets.CLUSTER_NAME_PRD }} --output text | grep Submission | grep -v Int | awk -F'/' '{print $2}')"
      - name: Deploy services with new task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ steps.set-service-output.outputs.service }}
          cluster: ${{ secrets.CLUSTER_NAME_PRD }}
          wait-for-service-stability: false

  tag-distribution-image:
    name: "Tag the distribution image on ECR with the version"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TOOLING_PUSHECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TOOLING_PUSHECR }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: "Get tag value"
        id: get-tag-value
        run: |
          echo "::set-output name=tag::${{ github.event.release.tag_name }}"
      - name: "Pull image from ECR, tag it and push it"
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_HOST }}
          docker pull ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${GITHUB_SHA}
          docker tag ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${GITHUB_SHA} ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${{ steps.get-tag-value.outputs.tag }}
          docker push ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${{ steps.get-tag-value.outputs.tag }}

  deploy-prd-distribution:
    name: "Deploy the distribution service to the prd environment"
    runs-on: ubuntu-latest
    needs:
      - tag-distribution-image
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRD_PUSHECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD_PUSHECR }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Retrieve Task Definition for external service on PRD
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_FAMILY_DISTRIBUTION_PRD }} --query taskDefinition > task-definition.json
      - name: Show task definition
        run: |
          cat task-definition.json
      - name: Set image name as output
        id: set-image-output
        run: |
          echo "::set-output name=image::${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${GITHUB_SHA}"
      - name: Update Task Definition for PRD with new image
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: "${{ secrets.ECS_CONTAINER_NAME_DISTRIBUTION_PRD }}"
          image: "${{ steps.set-image-output.outputs.image }}"
        env:
          IMAGE: "${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${GITHUB_SHA}"
      - name: Deploy new task definition
        id: deploy-task-definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          wait-for-service-stability: false
      - name: Determine scheduled task name
        id: get-scheduled-task-name
        run: |
          SCHEDULEDTASKNAME=$(aws events list-rules --query "Rules[*]|[?contains(Name,'Distr')].Name" --output text)
          echo "::set-output name=scheduledtaskname::${SCHEDULEDTASKNAME}"
      - name: Create new target config for the distribution scheduled task
        id: update-scheduled-task-distribution
        run: |
          aws events list-targets-by-rule --rule "${{ steps.get-scheduled-task-name.outputs.scheduledtaskname }}" > targetdef.orig.json
          jq '.Targets[0].EcsParameters.TaskDefinitionArn = "${{ steps.deploy-task-definition.outputs.task-definition-arn }}"' targetdef.orig.json > targetdef.json
          aws events put-targets --cli-input-json file://targetdef.json --rule "${{ steps.get-scheduled-task-name.outputs.scheduledtaskname }}"

